### ISSUE TITLE
Please add member icons for both origins and classes tooltips

### ISSUE THREAD

**Issue by LazyZhu** [Antize/TFT-Overlay#1]
So  we can see all options.

**Comment by Antize** [comment]
Added in new update :
https://github.com/Antize/TFT-Overlay/releases/tag/0.5

**Comment by LazyZhu** [comment]
Nice work.
Here is my config file with recommended items list for champions which taken from  [tftactics](https://tftactics.gg/champions).
[MyProfile.zip](https://github.com/Antize/TFT-Overlay/files/3407086/MyProfile.zip)
You can include it when you release next version
Also suggest separate champion item list from MyProfile.xml to Items.xml, in the future we can support Items.xml auto update :)

**Comment by Antize** [comment]
Thank added :) 

Yes I can make Items.xml but user lost his profile items if we change Items.xml :)

**Comment by LazyZhu** [comment]
We can make  Items.xml  read only, the changed items setting keep in MyProfile.xml.

Another suggestion to origins and classes tooltips:
Can we make the member icons shown like `Only one type` on, making already selected  champion darker.

**Comment by Antize** [comment]
I don't understand...

**Comment by Antize** [comment]
Added in next update :)

**Comment by LazyZhu** [comment]
Well done, You really make playing tft game easier.
