### ISSUE TITLE
Add multiple sub profile for different level, and add icon for them for tooltips.

### ISSUE THREAD

**Issue by LazyZhu** [Antize/TFT-Overlay#2]
We can add icon to the right like this:

![10](https://user-images.githubusercontent.com/2244967/61589264-298f7b00-abda-11e9-9fa7-30a6281b9fde.png)

The tootip looks like this:
![02](https://user-images.githubusercontent.com/2244967/61589472-ebe02180-abdc-11e9-83be-7202a70d1ed8.png)

Tit edit interface like this:
![01](https://user-images.githubusercontent.com/2244967/61589486-103bfe00-abdd-11e9-968e-3c327fc082bc.png)

This will help a lot for champions/synergy evolution when level up.

**Comment by Antize** [comment]
I don't understand :) 

if you "Sort champion list" you can resize the window...

**Comment by Antize** [comment]
Ahh i think i understand but it's boring to do:) and player will be lost ^^

**Comment by LazyZhu** [comment]
Champions should keep changing for getting better team comps, it's a better way to  be able  to record and review playing process and most good online team comp guide also use the different early/mid/later team comps, like https://tftactics.gg/tierlist/team-comps, but current can't archive this.
![20190722040137](https://user-images.githubusercontent.com/2244967/61596389-7fddd780-ac35-11e9-809f-e6d0b300f2cc.png)

I know it's boring, but this is a great feature for the TFT beginners, and riot will keep adding new champions and synergys, meaning more
team comps, we should have notebook like feature to do that.

**Comment by Antize** [comment]
I added sub profile in next update but I don't know if you'll like it:)

**Comment by LazyZhu** [comment]
Thanks, I love it.
